In [362]:
import math
import numpy as np
from cvxopt import matrix, glpk, solvers
from cvxopt.modeling import variable, op, blas, dot

In [363]:
# reputation = matrix([0.93, 0.35, 0.78, 0.75, 0.83, 0.23, 0.73, 0.32, 0.91, 0.26], tc='d')
# cost = matrix([(110 if reputation[i] >= 0.7 else 60) if (reputation[i] >= 0.3) else 0 for i in range(len(reputation))], tc='d')
# budget = 320.
# x = variable(len(reputation), 'x')
# constraint1 = (dot(x, cost) <= budget)
# constraint2 = (sum(x) == 4)
# targetFunction = (-sum((x[i]*reputation[i] if cost[i] > 0 else 0) for i in range(len(reputation))))
# (status, result) = glpk.ilp()

In [364]:
amountOfJobs = 4
budget = 320.
reputationArray = [0.93, 0.35, 0.78, 0.75, 0.83, 0.23, 0.73, 0.32, 0.91, 0.26]

In [365]:
availableUsers = matrix(reputationArray, tc='d')
cost = matrix([(110 if availableUsers[i] >= 0.7 else 60) if (availableUsers[i] >= 0.3) else 0 for i in range(len(availableUsers))], tc='d')
inequalitiesLeftSide = matrix([cost.T], tc='d')
inequalitiesRightSide = matrix([budget], tc='d')
equalitiesLeftSide = matrix([[1] for i in range(len(availableUsers))], tc='d')
equalitiesRightSide = matrix([amountOfJobs], tc='d')
targetFunction = matrix([[availableUsers[i] if availableUsers[i] >= 0.3 else 0] for i in range(len(availableUsers))], tc='d')
(status, x) = glpk.ilp(c=-targetFunction, G=inequalitiesLeftSide, h=inequalitiesRightSide, A=equalitiesLeftSide, b=equalitiesRightSide, B=set(range(len(availableUsers))))
print(status)
print(x)
print(matrix([[x],[availableUsers], [cost]]))

optimal
[ 1.00e+00]
[ 1.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 0.00e+00]
[ 1.00e+00]
[ 1.00e+00]

[ 1.00e+00  9.30e-01  1.10e+02]
[ 1.00e+00  3.50e-01  6.00e+01]
[ 0.00e+00  7.80e-01  1.10e+02]
[ 0.00e+00  7.50e-01  1.10e+02]
[ 0.00e+00  8.30e-01  1.10e+02]
[ 0.00e+00  2.30e-01  0.00e+00]
[ 0.00e+00  7.30e-01  1.10e+02]
[ 0.00e+00  3.20e-01  6.00e+01]
[ 1.00e+00  9.10e-01  1.10e+02]
[ 1.00e+00  2.60e-01  0.00e+00]

